name: Deploy App  Oracle DB

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Build and Deploy
      env:
        ORACLE_USER: ${{ secrets.ORACLE_USER }}
        ORACLE_PASSWORD: ${{ secrets.ORACLE_PASSWORD }}
        ##ORACLE_CONNECTION_STRING: ${{ secrets.ORACLE_CONNECTION_STRING }}
      run: |
        
    - name: Deploy Application
      run: |
       
